name: Continuous Integration Workflow - Backend
on:
  pull_request:
    branches:
      - main # Run the workflow only on pull requests to the main branch
    paths:
      - 'backend/**' # Workflow triggered on changes to code within express directory
      - '.github/workflows/backend_ci.yml'

jobs:
  test:
    defaults:
        run:
            working-directory: ./frontend

    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.x]
          mongodb-version: ['5.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
    # Todolist: Implement backend code

    #   - name: Lint Codebase
    #     run: npm run lint