name: Backend CI Workflow

on:
  pull_request:
    branches:
      - master
    paths:
      - 'backend-flask/**'
      - '.github/workflows/backend_ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['5.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env for backend service
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DB_URL: ${{ secrets.DB_URL }}
          envkey_JWT_SCRET_KEY: ${{ secrets.JWT_SCRET_KEY }}
          directory: backend-flask
          file_name: .env
          fail_on_empty: false
    
  
      - name: Build Docker image
        run: docker build -t backend:latest .
        working-directory: backend-flask


      - name: Run Docker image
        run: docker run -d --name backend -p 5000:5000 backend:latest

      - name: Check running container
        run: docker ps