name: Continuous Integration Workflow - Overall
on:
  pull_request:
    branches:
      - main # Run the workflow only on pull requests to the main branch
    paths:
      - 'backend/**' # Workflow triggered on changes to code within express directory
      - 'frontend/**'
      - '.github/workflows/**'


jobs:
  test:
    defaults:
        run:
            working-directory: .

    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.x]
          mongodb-version: ['5.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        
      - name: Orchestrate microservices
        run: docker-compose -f "docker-compose.yml" up -d --build
        working-directory: ./